# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 384357425d0f16e9d6e8b27acc557cfbc90dc1244a9d2261983775e394ac45bef7cea9bebc63974a89624cd1a620ff1a71593139abb083b7713b9fdfa02f6942

test:
  secret_key_base: b39a0beae6f346d634aa1b816902546c4bdacc31ba9e84f77d6debd09f48c2ab2d345a43af60afe1e701e910822acb1ad2459edeee7a302c48afb76bd43f4583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
